name: mslice-env
channels:
  - conda-forge
  - mantid
  - mantid/label/nightly
dependencies:
  - coverage
  - coveralls=3.3.1
  - ipython
  - mock
  - openssl=1.1.*  # Pinned to the same version as Mantid
  - pip
  - pytest
  - pyqt
  - qtconsole
  - qtpy
