name: mslice
channels:
  - defaults
  - mantid
  - mantid/label/nightly
dependencies:
  - flake8
  - ipython
  - mantid
  - mantidqt
  - matplotlib
  - mock
  - numpy
  - numpy-base
  - pip
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - scipy
  - six
  - pip:
      - coverage
      - h5py
      - nose
      - pre-commit
      - pyyaml
