name: mslice-env
channels:
  - conda-forge
  - mantid
  - mantid/label/nightly
dependencies:
  - coverage
  - flake8
  - ipython
  - mock
  - pip
  - pyqt
  - qtconsole
  - qtpy
  - pip:
      - nose
