name: mslice-env
channels:
  - conda-forge
  - thomashampson/label/python310
dependencies:
  - coverage
  - coveralls=3.3.1  # Pinned to a version that works with more recent versions of coverage
  - ipython
  - mock
  - pip
  - pytest
  - pyqt
  - qtconsole
  - qtpy
  - python=3.10
