name: mslice-env
channels:
  - conda-forge
  - mantid
  - mantid/label/nightly
dependencies:
  - python=3.9.*
  - coverage
  - flake8
  - ipython
  - mock
  - pip
  - pyqt
  - qtconsole
  - qtpy
  - qt=5.15.8
  - pip:
      - nose
      - flake8-pyproject
      - flake8-bugbear
