name: mslice
channels:
  - default
dependencies:
  - flake8
  - ipython
  - matplotlib
  - mock
  - numpy
  - numpy-base
  - pip
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - scipy
  - six
  - pip:
      - coverage
      - h5py
      - nose
      - pre-commit
      - pyyaml
