name: mslice-env
channels:
  - conda-forge
  - mantid
  - mantid/label/nightly
dependencies:
  - coverage
  - coveralls
  - ipython
  - mock
  - pip
  - pytest
  - pyqt
  - qtconsole
  - qtpy
  - python=3.11
