[workspace]
name = "mslice"
channels = ["conda-forge"]
# when editing local copy of mslice-env and mantidnightly, will need to temporarily remove
# the platforms that you aren't working on
platforms = ["linux-64", "win-64", "osx-arm64",]

[dependencies]
python = "3.12.*"

[feature.mslice-env]
channels = [
    "conda-forge",
    "mantid",
    "mantid/label/nightly",
]

[feature.mslice-env.dependencies]
pyqt = "*"
qtpy = "*"
ipython = "*"
coverage = "*"
coveralls = "*"
mock = "*"
pytest = "*"

[feature.mantidnightly]
channels = [
    "conda-forge",
    "mantid/label/nightly",
]

[feature.mantidnightly.dependencies]
mantid = "*"
mantidqt = "*"
coverage = "*"
mock = "*"
pre-commit = "*"
pytest = "*"

[feature.mantidnightly.tasks]
test = """
xvfb-run --server-args='-screen 0 640x480x24' --auto-servernum \
coverage run -m pytest
"""
coverage = """
coveralls
coverage report
"""

[environments]
# Equivalent to environment.yml
mslice-env = ["mslice-env"]

# Equivalent to mslice-developer.yml
mantidnightly = ["mantidnightly"]