# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MSlice.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1194, 862)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.scrollArea = QtGui.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 912, 821))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.guiControls = QtGui.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guiControls.sizePolicy().hasHeightForWidth())
        self.guiControls.setSizePolicy(sizePolicy)
        self.guiControls.setMinimumSize(QtCore.QSize(0, 0))
        self.guiControls.setObjectName(_fromUtf8("guiControls"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.guiControls)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidgetFilesWorkspaces_2 = QtGui.QTabWidget(self.guiControls)
        self.tabWidgetFilesWorkspaces_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidgetFilesWorkspaces_2.setObjectName(_fromUtf8("tabWidgetFilesWorkspaces_2"))
        self.tabWidgetFilesWorkspacesPage2_2 = QtGui.QWidget()
        self.tabWidgetFilesWorkspacesPage2_2.setObjectName(_fromUtf8("tabWidgetFilesWorkspacesPage2_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabWidgetFilesWorkspacesPage2_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnWorkspaceSave = QtGui.QPushButton(self.tabWidgetFilesWorkspacesPage2_2)
        self.btnWorkspaceSave.setObjectName(_fromUtf8("btnWorkspaceSave"))
        self.gridLayout_3.addWidget(self.btnWorkspaceSave, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(354, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        self.label_107 = QtGui.QLabel(self.tabWidgetFilesWorkspacesPage2_2)
        self.label_107.setText(_fromUtf8(""))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_3.addWidget(self.label_107, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.tblWorkspaces = QtGui.QTableWidget(self.tabWidgetFilesWorkspacesPage2_2)
        self.tblWorkspaces.setEnabled(True)
        self.tblWorkspaces.setMinimumSize(QtCore.QSize(0, 0))
        self.tblWorkspaces.setSizeIncrement(QtCore.QSize(5, 5))
        self.tblWorkspaces.setDragEnabled(False)
        self.tblWorkspaces.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblWorkspaces.setRowCount(12)
        self.tblWorkspaces.setColumnCount(5)
        self.tblWorkspaces.setObjectName(_fromUtf8("tblWorkspaces"))
        item = QtGui.QTableWidgetItem()
        self.tblWorkspaces.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblWorkspaces.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblWorkspaces.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblWorkspaces.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblWorkspaces.setHorizontalHeaderItem(4, item)
        self.tblWorkspaces.horizontalHeader().setVisible(False)
        self.tblWorkspaces.horizontalHeader().setCascadingSectionResizes(True)
        self.tblWorkspaces.horizontalHeader().setDefaultSectionSize(100)
        self.tblWorkspaces.horizontalHeader().setSortIndicatorShown(True)
        self.tblWorkspaces.horizontalHeader().setStretchLastSection(True)
        self.tblWorkspaces.verticalHeader().setVisible(False)
        self.tblWorkspaces.verticalHeader().setCascadingSectionResizes(True)
        self.tblWorkspaces.verticalHeader().setDefaultSectionSize(18)
        self.tblWorkspaces.verticalHeader().setHighlightSections(True)
        self.tblWorkspaces.verticalHeader().setMinimumSectionSize(15)
        self.tblWorkspaces.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tblWorkspaces, 0, 1, 2, 3)
        self.btnWorkspaceRemove = QtGui.QPushButton(self.tabWidgetFilesWorkspacesPage2_2)
        self.btnWorkspaceRemove.setObjectName(_fromUtf8("btnWorkspaceRemove"))
        self.gridLayout_3.addWidget(self.btnWorkspaceRemove, 2, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabWidgetFilesWorkspacesPage2_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btnLoad = QtGui.QPushButton(self.groupBox_4)
        self.btnLoad.setGeometry(QtCore.QRect(20, 30, 80, 23))
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.btnWorkspaceGroup = QtGui.QPushButton(self.groupBox_4)
        self.btnWorkspaceGroup.setGeometry(QtCore.QRect(20, 60, 81, 23))
        self.btnWorkspaceGroup.setObjectName(_fromUtf8("btnWorkspaceGroup"))
        self.btnWorkspaceCompose = QtGui.QPushButton(self.groupBox_4)
        self.btnWorkspaceCompose.setGeometry(QtCore.QRect(20, 90, 80, 23))
        self.btnWorkspaceCompose.setObjectName(_fromUtf8("btnWorkspaceCompose"))
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 5, 2, 1)
        self.tabWidgetFilesWorkspaces_2.addTab(self.tabWidgetFilesWorkspacesPage2_2, _fromUtf8(""))
        self.tabWidgetFilesWorkspacesPage1_2 = QtGui.QWidget()
        self.tabWidgetFilesWorkspacesPage1_2.setObjectName(_fromUtf8("tabWidgetFilesWorkspacesPage1_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tabWidgetFilesWorkspacesPage1_2)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.btnStatusLog = QtGui.QPushButton(self.tabWidgetFilesWorkspacesPage1_2)
        self.btnStatusLog.setObjectName(_fromUtf8("btnStatusLog"))
        self.gridLayout_14.addWidget(self.btnStatusLog, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem2, 0, 1, 1, 1)
        self.labelStatus_2 = QtGui.QLabel(self.tabWidgetFilesWorkspacesPage1_2)
        self.labelStatus_2.setObjectName(_fromUtf8("labelStatus_2"))
        self.gridLayout_14.addWidget(self.labelStatus_2, 0, 0, 1, 1)
        self.txtStatusLog = QtGui.QTextEdit(self.tabWidgetFilesWorkspacesPage1_2)
        self.txtStatusLog.setReadOnly(True)
        self.txtStatusLog.setObjectName(_fromUtf8("txtStatusLog"))
        self.gridLayout_14.addWidget(self.txtStatusLog, 1, 0, 1, 3)
        self.gridLayout_18.addLayout(self.gridLayout_14, 0, 0, 2, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.tabWidgetFilesWorkspacesPage1_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_132 = QtGui.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_132.setFont(font)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.gridLayout_17.addWidget(self.label_132, 0, 0, 1, 2)
        self.prgStatusMemory = QtGui.QProgressBar(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prgStatusMemory.sizePolicy().hasHeightForWidth())
        self.prgStatusMemory.setSizePolicy(sizePolicy)
        self.prgStatusMemory.setProperty("value", 24)
        self.prgStatusMemory.setObjectName(_fromUtf8("prgStatusMemory"))
        self.gridLayout_17.addWidget(self.prgStatusMemory, 0, 2, 1, 1)
        self.labelMaxMem_2 = QtGui.QLabel(self.groupBox_11)
        self.labelMaxMem_2.setObjectName(_fromUtf8("labelMaxMem_2"))
        self.gridLayout_17.addWidget(self.labelMaxMem_2, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(77, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem3, 1, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_17)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_164 = QtGui.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_164.setFont(font)
        self.label_164.setObjectName(_fromUtf8("label_164"))
        self.gridLayout_16.addWidget(self.label_164, 0, 0, 1, 1)
        self.prgStatusCPUUsage = QtGui.QProgressBar(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prgStatusCPUUsage.sizePolicy().hasHeightForWidth())
        self.prgStatusCPUUsage.setSizePolicy(sizePolicy)
        self.prgStatusCPUUsage.setProperty("value", 24)
        self.prgStatusCPUUsage.setObjectName(_fromUtf8("prgStatusCPUUsage"))
        self.gridLayout_16.addWidget(self.prgStatusCPUUsage, 0, 1, 2, 1)
        self.labelCPUCount_2 = QtGui.QLabel(self.groupBox_11)
        self.labelCPUCount_2.setObjectName(_fromUtf8("labelCPUCount_2"))
        self.gridLayout_16.addWidget(self.labelCPUCount_2, 1, 0, 2, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem4, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_16)
        self.gridLayout_18.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tabWidgetFilesWorkspacesPage1_2)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.labelElapsedTime_2 = QtGui.QLabel(self.groupBox_7)
        self.labelElapsedTime_2.setObjectName(_fromUtf8("labelElapsedTime_2"))
        self.gridLayout_15.addWidget(self.labelElapsedTime_2, 1, 0, 1, 2)
        self.label_108 = QtGui.QLabel(self.groupBox_7)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_15.addWidget(self.label_108, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(277, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 1, 2, 1, 1)
        self.prgStatusProgress = QtGui.QProgressBar(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prgStatusProgress.sizePolicy().hasHeightForWidth())
        self.prgStatusProgress.setSizePolicy(sizePolicy)
        self.prgStatusProgress.setProperty("value", 24)
        self.prgStatusProgress.setObjectName(_fromUtf8("prgStatusProgress"))
        self.gridLayout_15.addWidget(self.prgStatusProgress, 0, 1, 1, 3)
        self.gridLayout_18.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.tabWidgetFilesWorkspaces_2.addTab(self.tabWidgetFilesWorkspacesPage1_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidgetFilesWorkspaces_2)
        self.SampleTabWidget_2 = QtGui.QTabWidget(self.guiControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleTabWidget_2.sizePolicy().hasHeightForWidth())
        self.SampleTabWidget_2.setSizePolicy(sizePolicy)
        self.SampleTabWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.SampleTabWidget_2.setObjectName(_fromUtf8("SampleTabWidget_2"))
        self.PowderTab_3 = QtGui.QWidget()
        self.PowderTab_3.setObjectName(_fromUtf8("PowderTab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.PowderTab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.PowderTab_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_208 = QtGui.QLabel(self.groupBox)
        self.label_208.setObjectName(_fromUtf8("label_208"))
        self.gridLayout.addWidget(self.label_208, 0, 0, 1, 1)
        self.cmbPowderU1 = QtGui.QComboBox(self.groupBox)
        self.cmbPowderU1.setObjectName(_fromUtf8("cmbPowderU1"))
        self.cmbPowderU1.addItem(_fromUtf8(""))
        self.cmbPowderU1.addItem(_fromUtf8(""))
        self.cmbPowderU1.addItem(_fromUtf8(""))
        self.cmbPowderU1.addItem(_fromUtf8(""))
        self.cmbPowderU1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPowderU1, 0, 1, 1, 1)
        self.label_210 = QtGui.QLabel(self.groupBox)
        self.label_210.setObjectName(_fromUtf8("label_210"))
        self.gridLayout.addWidget(self.label_210, 1, 0, 1, 1)
        self.cmbPowderU2 = QtGui.QComboBox(self.groupBox)
        self.cmbPowderU2.setObjectName(_fromUtf8("cmbPowderU2"))
        self.cmbPowderU2.addItem(_fromUtf8(""))
        self.cmbPowderU2.addItem(_fromUtf8(""))
        self.cmbPowderU2.addItem(_fromUtf8(""))
        self.cmbPowderU2.addItem(_fromUtf8(""))
        self.cmbPowderU2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPowderU2, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.cmbPowderUnits = QtGui.QComboBox(self.groupBox)
        self.cmbPowderUnits.setObjectName(_fromUtf8("cmbPowderUnits"))
        self.gridLayout.addWidget(self.cmbPowderUnits, 1, 3, 1, 1)
        self.btnPowderCalculateProjection = QtGui.QPushButton(self.groupBox)
        self.btnPowderCalculateProjection.setObjectName(_fromUtf8("btnPowderCalculateProjection"))
        self.gridLayout.addWidget(self.btnPowderCalculateProjection, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 167, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 2, 1, 1)
        self.SampleTabWidget_2.addTab(self.PowderTab_3, _fromUtf8(""))
        self.SingleCrystalTab_3 = QtGui.QWidget()
        self.SingleCrystalTab_3.setObjectName(_fromUtf8("SingleCrystalTab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.SingleCrystalTab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnSingleCheckWorkspace = QtGui.QPushButton(self.SingleCrystalTab_3)
        self.btnSingleCheckWorkspace.setObjectName(_fromUtf8("btnSingleCheckWorkspace"))
        self.verticalLayout.addWidget(self.btnSingleCheckWorkspace)
        self.btnSingleSaveParams = QtGui.QPushButton(self.SingleCrystalTab_3)
        self.btnSingleSaveParams.setObjectName(_fromUtf8("btnSingleSaveParams"))
        self.verticalLayout.addWidget(self.btnSingleSaveParams)
        self.btnSingleLoadParams = QtGui.QPushButton(self.SingleCrystalTab_3)
        self.btnSingleLoadParams.setObjectName(_fromUtf8("btnSingleLoadParams"))
        self.verticalLayout.addWidget(self.btnSingleLoadParams)
        self.btnSingleDefaultParams = QtGui.QPushButton(self.SingleCrystalTab_3)
        self.btnSingleDefaultParams.setObjectName(_fromUtf8("btnSingleDefaultParams"))
        self.verticalLayout.addWidget(self.btnSingleDefaultParams)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 2, 3, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem11, 1, 3, 1, 1)
        self.groupBoxViewingAxes_3 = QtGui.QGroupBox(self.SingleCrystalTab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxViewingAxes_3.sizePolicy().hasHeightForWidth())
        self.groupBoxViewingAxes_3.setSizePolicy(sizePolicy)
        self.groupBoxViewingAxes_3.setMinimumSize(QtCore.QSize(0, 114))
        self.groupBoxViewingAxes_3.setObjectName(_fromUtf8("groupBoxViewingAxes_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxViewingAxes_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_218 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_218.setObjectName(_fromUtf8("label_218"))
        self.gridLayout_9.addWidget(self.label_218, 0, 1, 1, 1)
        self.label_216 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_216.setObjectName(_fromUtf8("label_216"))
        self.gridLayout_9.addWidget(self.label_216, 0, 2, 1, 1)
        self.label_217 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_217.setObjectName(_fromUtf8("label_217"))
        self.gridLayout_9.addWidget(self.label_217, 0, 3, 1, 1)
        self.label_219 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_219.setObjectName(_fromUtf8("label_219"))
        self.gridLayout_9.addWidget(self.label_219, 0, 4, 1, 1)
        self.label_220 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_220.setEnabled(False)
        self.label_220.setObjectName(_fromUtf8("label_220"))
        self.gridLayout_9.addWidget(self.label_220, 0, 5, 1, 1)
        self.label_221 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_221.setEnabled(False)
        self.label_221.setObjectName(_fromUtf8("label_221"))
        self.gridLayout_9.addWidget(self.label_221, 0, 6, 1, 1)
        self.label_222 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_222.setEnabled(False)
        self.label_222.setObjectName(_fromUtf8("label_222"))
        self.gridLayout_9.addWidget(self.label_222, 0, 7, 1, 1)
        self.label_214 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_214.setObjectName(_fromUtf8("label_214"))
        self.gridLayout_9.addWidget(self.label_214, 1, 0, 1, 1)
        self.lneSingleAU1 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleAU1.sizePolicy().hasHeightForWidth())
        self.lneSingleAU1.setSizePolicy(sizePolicy)
        self.lneSingleAU1.setObjectName(_fromUtf8("lneSingleAU1"))
        self.gridLayout_9.addWidget(self.lneSingleAU1, 1, 1, 1, 1)
        self.lneSingleBU1 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleBU1.sizePolicy().hasHeightForWidth())
        self.lneSingleBU1.setSizePolicy(sizePolicy)
        self.lneSingleBU1.setObjectName(_fromUtf8("lneSingleBU1"))
        self.gridLayout_9.addWidget(self.lneSingleBU1, 1, 2, 1, 1)
        self.lneSingleCU1 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleCU1.sizePolicy().hasHeightForWidth())
        self.lneSingleCU1.setSizePolicy(sizePolicy)
        self.lneSingleCU1.setObjectName(_fromUtf8("lneSingleCU1"))
        self.gridLayout_9.addWidget(self.lneSingleCU1, 1, 3, 1, 1)
        self.lneSingleU1Label = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleU1Label.sizePolicy().hasHeightForWidth())
        self.lneSingleU1Label.setSizePolicy(sizePolicy)
        self.lneSingleU1Label.setObjectName(_fromUtf8("lneSingleU1Label"))
        self.gridLayout_9.addWidget(self.lneSingleU1Label, 1, 4, 1, 1)
        self.chkSingleU1Fold = QtGui.QCheckBox(self.groupBoxViewingAxes_3)
        self.chkSingleU1Fold.setEnabled(False)
        self.chkSingleU1Fold.setText(_fromUtf8(""))
        self.chkSingleU1Fold.setTristate(False)
        self.chkSingleU1Fold.setObjectName(_fromUtf8("chkSingleU1Fold"))
        self.gridLayout_9.addWidget(self.chkSingleU1Fold, 1, 5, 1, 1)
        self.lneSingleU1Center = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        self.lneSingleU1Center.setEnabled(False)
        self.lneSingleU1Center.setObjectName(_fromUtf8("lneSingleU1Center"))
        self.gridLayout_9.addWidget(self.lneSingleU1Center, 1, 6, 1, 1)
        self.cmbSingleU1Direction = QtGui.QComboBox(self.groupBoxViewingAxes_3)
        self.cmbSingleU1Direction.setEnabled(False)
        self.cmbSingleU1Direction.setObjectName(_fromUtf8("cmbSingleU1Direction"))
        self.cmbSingleU1Direction.addItem(_fromUtf8(""))
        self.cmbSingleU1Direction.addItem(_fromUtf8(""))
        self.cmbSingleU1Direction.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbSingleU1Direction, 1, 7, 1, 1)
        self.label_215 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_215.setObjectName(_fromUtf8("label_215"))
        self.gridLayout_9.addWidget(self.label_215, 2, 0, 1, 1)
        self.lneSingleAU2 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleAU2.sizePolicy().hasHeightForWidth())
        self.lneSingleAU2.setSizePolicy(sizePolicy)
        self.lneSingleAU2.setObjectName(_fromUtf8("lneSingleAU2"))
        self.gridLayout_9.addWidget(self.lneSingleAU2, 2, 1, 1, 1)
        self.lneSingleBU2 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleBU2.sizePolicy().hasHeightForWidth())
        self.lneSingleBU2.setSizePolicy(sizePolicy)
        self.lneSingleBU2.setObjectName(_fromUtf8("lneSingleBU2"))
        self.gridLayout_9.addWidget(self.lneSingleBU2, 2, 2, 1, 1)
        self.lneSingleCU2 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleCU2.sizePolicy().hasHeightForWidth())
        self.lneSingleCU2.setSizePolicy(sizePolicy)
        self.lneSingleCU2.setObjectName(_fromUtf8("lneSingleCU2"))
        self.gridLayout_9.addWidget(self.lneSingleCU2, 2, 3, 1, 1)
        self.lneSingleU2Label = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleU2Label.sizePolicy().hasHeightForWidth())
        self.lneSingleU2Label.setSizePolicy(sizePolicy)
        self.lneSingleU2Label.setObjectName(_fromUtf8("lneSingleU2Label"))
        self.gridLayout_9.addWidget(self.lneSingleU2Label, 2, 4, 1, 1)
        self.chkSingleU2Fold = QtGui.QCheckBox(self.groupBoxViewingAxes_3)
        self.chkSingleU2Fold.setEnabled(False)
        self.chkSingleU2Fold.setText(_fromUtf8(""))
        self.chkSingleU2Fold.setObjectName(_fromUtf8("chkSingleU2Fold"))
        self.gridLayout_9.addWidget(self.chkSingleU2Fold, 2, 5, 1, 1)
        self.lneSingleU2Center = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        self.lneSingleU2Center.setEnabled(False)
        self.lneSingleU2Center.setObjectName(_fromUtf8("lneSingleU2Center"))
        self.gridLayout_9.addWidget(self.lneSingleU2Center, 2, 6, 1, 1)
        self.cmbSingleU2Direction = QtGui.QComboBox(self.groupBoxViewingAxes_3)
        self.cmbSingleU2Direction.setEnabled(False)
        self.cmbSingleU2Direction.setObjectName(_fromUtf8("cmbSingleU2Direction"))
        self.cmbSingleU2Direction.addItem(_fromUtf8(""))
        self.cmbSingleU2Direction.addItem(_fromUtf8(""))
        self.cmbSingleU2Direction.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbSingleU2Direction, 2, 7, 1, 1)
        self.label_223 = QtGui.QLabel(self.groupBoxViewingAxes_3)
        self.label_223.setObjectName(_fromUtf8("label_223"))
        self.gridLayout_9.addWidget(self.label_223, 3, 0, 1, 1)
        self.lneSingleAU3 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleAU3.sizePolicy().hasHeightForWidth())
        self.lneSingleAU3.setSizePolicy(sizePolicy)
        self.lneSingleAU3.setObjectName(_fromUtf8("lneSingleAU3"))
        self.gridLayout_9.addWidget(self.lneSingleAU3, 3, 1, 1, 1)
        self.lneSingleBU3 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleBU3.sizePolicy().hasHeightForWidth())
        self.lneSingleBU3.setSizePolicy(sizePolicy)
        self.lneSingleBU3.setObjectName(_fromUtf8("lneSingleBU3"))
        self.gridLayout_9.addWidget(self.lneSingleBU3, 3, 2, 1, 1)
        self.lneSingleCU3 = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleCU3.sizePolicy().hasHeightForWidth())
        self.lneSingleCU3.setSizePolicy(sizePolicy)
        self.lneSingleCU3.setObjectName(_fromUtf8("lneSingleCU3"))
        self.gridLayout_9.addWidget(self.lneSingleCU3, 3, 3, 1, 1)
        self.lneSingleU3Label = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lneSingleU3Label.sizePolicy().hasHeightForWidth())
        self.lneSingleU3Label.setSizePolicy(sizePolicy)
        self.lneSingleU3Label.setObjectName(_fromUtf8("lneSingleU3Label"))
        self.gridLayout_9.addWidget(self.lneSingleU3Label, 3, 4, 1, 1)
        self.chkSingleU3Fold = QtGui.QCheckBox(self.groupBoxViewingAxes_3)
        self.chkSingleU3Fold.setEnabled(False)
        self.chkSingleU3Fold.setText(_fromUtf8(""))
        self.chkSingleU3Fold.setObjectName(_fromUtf8("chkSingleU3Fold"))
        self.gridLayout_9.addWidget(self.chkSingleU3Fold, 3, 5, 1, 1)
        self.lneSingleU3Center = QtGui.QLineEdit(self.groupBoxViewingAxes_3)
        self.lneSingleU3Center.setEnabled(False)
        self.lneSingleU3Center.setObjectName(_fromUtf8("lneSingleU3Center"))
        self.gridLayout_9.addWidget(self.lneSingleU3Center, 3, 6, 1, 1)
        self.cmbSingleU3Direction = QtGui.QComboBox(self.groupBoxViewingAxes_3)
        self.cmbSingleU3Direction.setEnabled(False)
        self.cmbSingleU3Direction.setObjectName(_fromUtf8("cmbSingleU3Direction"))
        self.cmbSingleU3Direction.addItem(_fromUtf8(""))
        self.cmbSingleU3Direction.addItem(_fromUtf8(""))
        self.cmbSingleU3Direction.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmbSingleU3Direction, 3, 7, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxViewingAxes_3, 2, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.SingleCrystalTab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblSingleEi = QtGui.QLabel(self.groupBox_16)
        self.lblSingleEi.setObjectName(_fromUtf8("lblSingleEi"))
        self.horizontalLayout_2.addWidget(self.lblSingleEi)
        self.lblSingleStartAngle = QtGui.QLabel(self.groupBox_16)
        self.lblSingleStartAngle.setObjectName(_fromUtf8("lblSingleStartAngle"))
        self.horizontalLayout_2.addWidget(self.lblSingleStartAngle)
        self.gridLayout_8.addWidget(self.groupBox_16, 1, 1, 1, 1)
        self.widget = QtGui.QWidget(self.SingleCrystalTab_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 117))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 1, 1, 1, 1)
        self.btnSingleCalculateProjections = QtGui.QPushButton(self.widget)
        self.btnSingleCalculateProjections.setObjectName(_fromUtf8("btnSingleCalculateProjections"))
        self.gridLayout_7.addWidget(self.btnSingleCalculateProjections, 1, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.widget)
        self.groupBox_14.setMinimumSize(QtCore.QSize(171, 70))
        self.groupBox_14.setTitle(_fromUtf8(""))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.lneSingleWorkspacePrefix = QtGui.QLineEdit(self.groupBox_14)
        self.lneSingleWorkspacePrefix.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.lneSingleWorkspacePrefix.setObjectName(_fromUtf8("lneSingleWorkspacePrefix"))
        self.label_233 = QtGui.QLabel(self.groupBox_14)
        self.label_233.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_233.setObjectName(_fromUtf8("label_233"))
        self.gridLayout_7.addWidget(self.groupBox_14, 0, 0, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(37, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.widget, 2, 1, 1, 1)
        self.groupBoxSCUnitCellLatticeParams_3 = QtGui.QGroupBox(self.SingleCrystalTab_3)
        self.groupBoxSCUnitCellLatticeParams_3.setObjectName(_fromUtf8("groupBoxSCUnitCellLatticeParams_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxSCUnitCellLatticeParams_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_224 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        self.label_224.setObjectName(_fromUtf8("label_224"))
        self.gridLayout_4.addWidget(self.label_224, 0, 0, 1, 1)
        self.lneSingleA = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleA.setObjectName(_fromUtf8("lneSingleA"))
        self.gridLayout_4.addWidget(self.lneSingleA, 0, 1, 1, 1)
        self.label_225 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        self.label_225.setObjectName(_fromUtf8("label_225"))
        self.gridLayout_4.addWidget(self.label_225, 0, 2, 1, 1)
        self.lneSingleB = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleB.setObjectName(_fromUtf8("lneSingleB"))
        self.gridLayout_4.addWidget(self.lneSingleB, 0, 3, 1, 1)
        self.label_226 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        self.label_226.setObjectName(_fromUtf8("label_226"))
        self.gridLayout_4.addWidget(self.label_226, 0, 4, 1, 1)
        self.lneSingleC = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleC.setObjectName(_fromUtf8("lneSingleC"))
        self.gridLayout_4.addWidget(self.lneSingleC, 0, 5, 1, 1)
        self.labelSCUCalpha_2 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.labelSCUCalpha_2.setFont(font)
        self.labelSCUCalpha_2.setObjectName(_fromUtf8("labelSCUCalpha_2"))
        self.gridLayout_4.addWidget(self.labelSCUCalpha_2, 1, 0, 1, 1)
        self.lneSingleAlpha = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleAlpha.setObjectName(_fromUtf8("lneSingleAlpha"))
        self.gridLayout_4.addWidget(self.lneSingleAlpha, 1, 1, 1, 1)
        self.labelSCUCbeta_2 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.labelSCUCbeta_2.setFont(font)
        self.labelSCUCbeta_2.setObjectName(_fromUtf8("labelSCUCbeta_2"))
        self.gridLayout_4.addWidget(self.labelSCUCbeta_2, 1, 2, 1, 1)
        self.lneSingleBeta = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleBeta.setObjectName(_fromUtf8("lneSingleBeta"))
        self.gridLayout_4.addWidget(self.lneSingleBeta, 1, 3, 1, 1)
        self.labelSCUCgamma_2 = QtGui.QLabel(self.groupBoxSCUnitCellLatticeParams_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.labelSCUCgamma_2.setFont(font)
        self.labelSCUCgamma_2.setObjectName(_fromUtf8("labelSCUCgamma_2"))
        self.gridLayout_4.addWidget(self.labelSCUCgamma_2, 1, 4, 1, 1)
        self.lneSingleGamma = QtGui.QLineEdit(self.groupBoxSCUnitCellLatticeParams_3)
        self.lneSingleGamma.setObjectName(_fromUtf8("lneSingleGamma"))
        self.gridLayout_4.addWidget(self.lneSingleGamma, 1, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxSCUnitCellLatticeParams_3, 0, 0, 1, 1)
        self.groupBoxSCCrystalOrientation_3 = QtGui.QGroupBox(self.SingleCrystalTab_3)
        self.groupBoxSCCrystalOrientation_3.setObjectName(_fromUtf8("groupBoxSCCrystalOrientation_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxSCCrystalOrientation_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_227 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_227.setObjectName(_fromUtf8("label_227"))
        self.gridLayout_5.addWidget(self.label_227, 0, 0, 1, 1)
        self.lneSingleVz = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleVz.setObjectName(_fromUtf8("lneSingleVz"))
        self.gridLayout_5.addWidget(self.lneSingleVz, 1, 5, 1, 1)
        self.lneSingleUz1 = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleUz1.setObjectName(_fromUtf8("lneSingleUz1"))
        self.gridLayout_5.addWidget(self.lneSingleUz1, 0, 5, 1, 1)
        self.label_229 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_229.setObjectName(_fromUtf8("label_229"))
        self.gridLayout_5.addWidget(self.label_229, 0, 4, 1, 1)
        self.label_232 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_232.setObjectName(_fromUtf8("label_232"))
        self.gridLayout_5.addWidget(self.label_232, 1, 4, 1, 1)
        self.lneSingleVy = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleVy.setObjectName(_fromUtf8("lneSingleVy"))
        self.gridLayout_5.addWidget(self.lneSingleVy, 1, 3, 1, 1)
        self.label_231 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_231.setObjectName(_fromUtf8("label_231"))
        self.gridLayout_5.addWidget(self.label_231, 1, 2, 1, 1)
        self.label_228 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_228.setObjectName(_fromUtf8("label_228"))
        self.gridLayout_5.addWidget(self.label_228, 0, 2, 1, 1)
        self.lneSingleUy1 = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleUy1.setObjectName(_fromUtf8("lneSingleUy1"))
        self.gridLayout_5.addWidget(self.lneSingleUy1, 0, 3, 1, 1)
        self.lneSingleVx = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleVx.setObjectName(_fromUtf8("lneSingleVx"))
        self.gridLayout_5.addWidget(self.lneSingleVx, 1, 1, 1, 1)
        self.label_230 = QtGui.QLabel(self.groupBoxSCCrystalOrientation_3)
        self.label_230.setObjectName(_fromUtf8("label_230"))
        self.gridLayout_5.addWidget(self.label_230, 1, 0, 1, 1)
        self.lneSingleUx1 = QtGui.QLineEdit(self.groupBoxSCCrystalOrientation_3)
        self.lneSingleUx1.setObjectName(_fromUtf8("lneSingleUx1"))
        self.gridLayout_5.addWidget(self.lneSingleUx1, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxSCCrystalOrientation_3, 0, 1, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.SingleCrystalTab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_234 = QtGui.QLabel(self.groupBox_15)
        self.label_234.setObjectName(_fromUtf8("label_234"))
        self.gridLayout_6.addWidget(self.label_234, 0, 0, 1, 1)
        self.lneSinglePsiOffset = QtGui.QLineEdit(self.groupBox_15)
        self.lneSinglePsiOffset.setText(_fromUtf8(""))
        self.lneSinglePsiOffset.setObjectName(_fromUtf8("lneSinglePsiOffset"))
        self.gridLayout_6.addWidget(self.lneSinglePsiOffset, 0, 1, 1, 1)
        self.label_235 = QtGui.QLabel(self.groupBox_15)
        self.label_235.setObjectName(_fromUtf8("label_235"))
        self.gridLayout_6.addWidget(self.label_235, 0, 2, 1, 1)
        self.lneSingleMotorname = QtGui.QLineEdit(self.groupBox_15)
        self.lneSingleMotorname.setText(_fromUtf8(""))
        self.lneSingleMotorname.setObjectName(_fromUtf8("lneSingleMotorname"))
        self.gridLayout_6.addWidget(self.lneSingleMotorname, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_15, 1, 0, 1, 1)
        self.SampleTabWidget_2.addTab(self.SingleCrystalTab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.SampleTabWidget_2)
        self.ViewTabWidget_2 = QtGui.QTabWidget(self.guiControls)
        self.ViewTabWidget_2.setEnabled(True)
        self.ViewTabWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.ViewTabWidget_2.setObjectName(_fromUtf8("ViewTabWidget_2"))
        self.SliceTab_3 = QtGui.QWidget()
        self.SliceTab_3.setObjectName(_fromUtf8("SliceTab_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.SliceTab_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_10 = QtGui.QLabel(self.SliceTab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 0, 0, 1, 1)
        self.cmbSliceXAxis = QtGui.QComboBox(self.SliceTab_3)
        self.cmbSliceXAxis.setObjectName(_fromUtf8("cmbSliceXAxis"))
        self.gridLayout_10.addWidget(self.cmbSliceXAxis, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.SliceTab_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 0, 2, 1, 1)
        self.lneSliceXStart = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceXStart.setObjectName(_fromUtf8("lneSliceXStart"))
        self.gridLayout_10.addWidget(self.lneSliceXStart, 0, 3, 1, 1)
        self.label_267 = QtGui.QLabel(self.SliceTab_3)
        self.label_267.setObjectName(_fromUtf8("label_267"))
        self.gridLayout_10.addWidget(self.label_267, 0, 4, 1, 1)
        self.lneSliceXEnd = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceXEnd.setObjectName(_fromUtf8("lneSliceXEnd"))
        self.gridLayout_10.addWidget(self.lneSliceXEnd, 0, 5, 1, 2)
        self.label_268 = QtGui.QLabel(self.SliceTab_3)
        self.label_268.setObjectName(_fromUtf8("label_268"))
        self.gridLayout_10.addWidget(self.label_268, 0, 7, 1, 1)
        self.lneSliceXStep = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceXStep.setText(_fromUtf8(""))
        self.lneSliceXStep.setObjectName(_fromUtf8("lneSliceXStep"))
        self.gridLayout_10.addWidget(self.lneSliceXStep, 0, 8, 1, 1)
        self.label_11 = QtGui.QLabel(self.SliceTab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.cmbSliceYAxis = QtGui.QComboBox(self.SliceTab_3)
        self.cmbSliceYAxis.setObjectName(_fromUtf8("cmbSliceYAxis"))
        self.gridLayout_10.addWidget(self.cmbSliceYAxis, 1, 1, 1, 1)
        self.label_271 = QtGui.QLabel(self.SliceTab_3)
        self.label_271.setObjectName(_fromUtf8("label_271"))
        self.gridLayout_10.addWidget(self.label_271, 1, 2, 1, 1)
        self.lneSliceYStart = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceYStart.setObjectName(_fromUtf8("lneSliceYStart"))
        self.gridLayout_10.addWidget(self.lneSliceYStart, 1, 3, 1, 1)
        self.label_270 = QtGui.QLabel(self.SliceTab_3)
        self.label_270.setObjectName(_fromUtf8("label_270"))
        self.gridLayout_10.addWidget(self.label_270, 1, 4, 1, 1)
        self.lneSliceYEnd = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceYEnd.setObjectName(_fromUtf8("lneSliceYEnd"))
        self.gridLayout_10.addWidget(self.lneSliceYEnd, 1, 5, 1, 2)
        self.label_255 = QtGui.QLabel(self.SliceTab_3)
        self.label_255.setObjectName(_fromUtf8("label_255"))
        self.gridLayout_10.addWidget(self.label_255, 1, 7, 1, 1)
        self.lneSliceYStep = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceYStep.setText(_fromUtf8(""))
        self.lneSliceYStep.setObjectName(_fromUtf8("lneSliceYStep"))
        self.gridLayout_10.addWidget(self.lneSliceYStep, 1, 8, 1, 1)
        self.label_13 = QtGui.QLabel(self.SliceTab_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_10.addWidget(self.label_13, 2, 0, 1, 2)
        self.label_269 = QtGui.QLabel(self.SliceTab_3)
        self.label_269.setObjectName(_fromUtf8("label_269"))
        self.gridLayout_10.addWidget(self.label_269, 2, 2, 1, 1)
        self.lneSliceIntensityStart = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceIntensityStart.setObjectName(_fromUtf8("lneSliceIntensityStart"))
        self.gridLayout_10.addWidget(self.lneSliceIntensityStart, 2, 3, 1, 1)
        self.label_266 = QtGui.QLabel(self.SliceTab_3)
        self.label_266.setObjectName(_fromUtf8("label_266"))
        self.gridLayout_10.addWidget(self.label_266, 2, 4, 1, 1)
        self.lneSliceIntensityEnd = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceIntensityEnd.setObjectName(_fromUtf8("lneSliceIntensityEnd"))
        self.gridLayout_10.addWidget(self.lneSliceIntensityEnd, 2, 5, 1, 2)
        self.rdoSliceNormToOne = QtGui.QRadioButton(self.SliceTab_3)
        self.rdoSliceNormToOne.setObjectName(_fromUtf8("rdoSliceNormToOne"))
        self.gridLayout_10.addWidget(self.rdoSliceNormToOne, 2, 7, 1, 2)
        self.label_14 = QtGui.QLabel(self.SliceTab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 3, 0, 1, 2)
        self.lneSliceSmoothing = QtGui.QLineEdit(self.SliceTab_3)
        self.lneSliceSmoothing.setObjectName(_fromUtf8("lneSliceSmoothing"))
        self.gridLayout_10.addWidget(self.lneSliceSmoothing, 3, 2, 1, 2)
        self.cmbSliceColormap = QtGui.QComboBox(self.SliceTab_3)
        self.cmbSliceColormap.setObjectName(_fromUtf8("cmbSliceColormap"))
        self.gridLayout_10.addWidget(self.cmbSliceColormap, 3, 8, 1, 1)
        self.label_15 = QtGui.QLabel(self.SliceTab_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 3, 7, 1, 1)
        self.btnSliceDisplay = QtGui.QPushButton(self.SliceTab_3)
        self.btnSliceDisplay.setObjectName(_fromUtf8("btnSliceDisplay"))
        self.gridLayout_10.addWidget(self.btnSliceDisplay, 4, 8, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem14, 0, 1, 1, 1)
        self.ViewTabWidget_2.addTab(self.SliceTab_3, _fromUtf8(""))
        self.CutTab_3 = QtGui.QWidget()
        self.CutTab_3.setObjectName(_fromUtf8("CutTab_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.CutTab_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_251 = QtGui.QLabel(self.CutTab_3)
        self.label_251.setObjectName(_fromUtf8("label_251"))
        self.gridLayout_12.addWidget(self.label_251, 0, 0, 1, 1)
        self.cmbCutAxis = QtGui.QComboBox(self.CutTab_3)
        self.cmbCutAxis.setObjectName(_fromUtf8("cmbCutAxis"))
        self.gridLayout_12.addWidget(self.cmbCutAxis, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.CutTab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_12.addWidget(self.label_4, 0, 2, 1, 1)
        self.lneCutStart = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutStart.setObjectName(_fromUtf8("lneCutStart"))
        self.gridLayout_12.addWidget(self.lneCutStart, 0, 3, 1, 1)
        self.label_257 = QtGui.QLabel(self.CutTab_3)
        self.label_257.setObjectName(_fromUtf8("label_257"))
        self.gridLayout_12.addWidget(self.label_257, 0, 4, 1, 1)
        self.lneCutEnd = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutEnd.setObjectName(_fromUtf8("lneCutEnd"))
        self.gridLayout_12.addWidget(self.lneCutEnd, 0, 5, 1, 1)
        self.label_256 = QtGui.QLabel(self.CutTab_3)
        self.label_256.setObjectName(_fromUtf8("label_256"))
        self.gridLayout_12.addWidget(self.label_256, 0, 6, 1, 1)
        self.lneCutStep = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutStep.setText(_fromUtf8(""))
        self.lneCutStep.setObjectName(_fromUtf8("lneCutStep"))
        self.gridLayout_12.addWidget(self.lneCutStep, 0, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.CutTab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_12.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_258 = QtGui.QLabel(self.CutTab_3)
        self.label_258.setObjectName(_fromUtf8("label_258"))
        self.gridLayout_12.addWidget(self.label_258, 1, 2, 1, 1)
        self.lneCutIntegrationStart = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutIntegrationStart.setObjectName(_fromUtf8("lneCutIntegrationStart"))
        self.gridLayout_12.addWidget(self.lneCutIntegrationStart, 1, 3, 1, 1)
        self.label_259 = QtGui.QLabel(self.CutTab_3)
        self.label_259.setObjectName(_fromUtf8("label_259"))
        self.gridLayout_12.addWidget(self.label_259, 1, 4, 1, 1)
        self.lneCutIntegrationEnd = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutIntegrationEnd.setObjectName(_fromUtf8("lneCutIntegrationEnd"))
        self.gridLayout_12.addWidget(self.lneCutIntegrationEnd, 1, 5, 1, 1)
        self.label_253 = QtGui.QLabel(self.CutTab_3)
        self.label_253.setObjectName(_fromUtf8("label_253"))
        self.gridLayout_12.addWidget(self.label_253, 1, 6, 1, 1)
        self.lneCutIntegrationWidth = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutIntegrationWidth.setText(_fromUtf8(""))
        self.lneCutIntegrationWidth.setObjectName(_fromUtf8("lneCutIntegrationWidth"))
        self.gridLayout_12.addWidget(self.lneCutIntegrationWidth, 1, 7, 1, 1)
        self.label_3 = QtGui.QLabel(self.CutTab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_12.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_264 = QtGui.QLabel(self.CutTab_3)
        self.label_264.setObjectName(_fromUtf8("label_264"))
        self.gridLayout_12.addWidget(self.label_264, 2, 2, 1, 1)
        self.lneEditCutIntensityStart = QtGui.QLineEdit(self.CutTab_3)
        self.lneEditCutIntensityStart.setObjectName(_fromUtf8("lneEditCutIntensityStart"))
        self.gridLayout_12.addWidget(self.lneEditCutIntensityStart, 2, 3, 1, 1)
        self.label_265 = QtGui.QLabel(self.CutTab_3)
        self.label_265.setObjectName(_fromUtf8("label_265"))
        self.gridLayout_12.addWidget(self.label_265, 2, 4, 1, 1)
        self.lneCutIntensityEnd = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutIntensityEnd.setObjectName(_fromUtf8("lneCutIntensityEnd"))
        self.gridLayout_12.addWidget(self.lneCutIntensityEnd, 2, 5, 1, 1)
        self.rdoCutNormToOne = QtGui.QRadioButton(self.CutTab_3)
        self.rdoCutNormToOne.setObjectName(_fromUtf8("rdoCutNormToOne"))
        self.gridLayout_12.addWidget(self.rdoCutNormToOne, 2, 6, 1, 2)
        self.label_5 = QtGui.QLabel(self.CutTab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_12.addWidget(self.label_5, 3, 1, 1, 1)
        self.lneCutSmoothing = QtGui.QLineEdit(self.CutTab_3)
        self.lneCutSmoothing.setObjectName(_fromUtf8("lneCutSmoothing"))
        self.gridLayout_12.addWidget(self.lneCutSmoothing, 3, 2, 1, 2)
        self.btnCutPlot = QtGui.QPushButton(self.CutTab_3)
        self.btnCutPlot.setObjectName(_fromUtf8("btnCutPlot"))
        self.gridLayout_12.addWidget(self.btnCutPlot, 3, 6, 1, 2)
        self.btnCutSaveAscii = QtGui.QPushButton(self.CutTab_3)
        self.btnCutSaveAscii.setObjectName(_fromUtf8("btnCutSaveAscii"))
        self.gridLayout_12.addWidget(self.btnCutSaveAscii, 4, 0, 1, 2)
        self.btnCutSaveToWorkspace = QtGui.QPushButton(self.CutTab_3)
        self.btnCutSaveToWorkspace.setObjectName(_fromUtf8("btnCutSaveToWorkspace"))
        self.gridLayout_12.addWidget(self.btnCutSaveToWorkspace, 4, 3, 1, 3)
        self.btnCutPlotOver = QtGui.QPushButton(self.CutTab_3)
        self.btnCutPlotOver.setObjectName(_fromUtf8("btnCutPlotOver"))
        self.gridLayout_12.addWidget(self.btnCutPlotOver, 4, 6, 1, 2)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(122, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem15, 0, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem16, 1, 0, 1, 1)
        self.ViewTabWidget_2.addTab(self.CutTab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.ViewTabWidget_2)
        self.horizontalLayout_4.addWidget(self.guiControls)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtGui.QScrollArea(self.splitter)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 276, 804))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.iPythonPlaceHolder = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iPythonPlaceHolder.sizePolicy().hasHeightForWidth())
        self.iPythonPlaceHolder.setSizePolicy(sizePolicy)
        self.iPythonPlaceHolder.setObjectName(_fromUtf8("iPythonPlaceHolder"))
        self.horizontalLayout.addWidget(self.iPythonPlaceHolder)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuDelete = QtGui.QMenu(self.menuFile)
        self.menuDelete.setObjectName(_fromUtf8("menuDelete"))
        self.menuParameters = QtGui.QMenu(self.menubar)
        self.menuParameters.setObjectName(_fromUtf8("menuParameters"))
        self.menuBackground = QtGui.QMenu(self.menubar)
        self.menuBackground.setObjectName(_fromUtf8("menuBackground"))
        self.menuMask = QtGui.QMenu(self.menubar)
        self.menuMask.setObjectName(_fromUtf8("menuMask"))
        self.menuSet_Mask = QtGui.QMenu(self.menuMask)
        self.menuSet_Mask.setObjectName(_fromUtf8("menuSet_Mask"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuInstrument_Geometry = QtGui.QMenu(self.menuOptions)
        self.menuInstrument_Geometry.setObjectName(_fromUtf8("menuInstrument_Geometry"))
        self.menuVeiw_Intensity_As = QtGui.QMenu(self.menuOptions)
        self.menuVeiw_Intensity_As.setObjectName(_fromUtf8("menuVeiw_Intensity_As"))
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_Parameters = QtGui.QAction(MainWindow)
        self.actionLoad_Parameters.setObjectName(_fromUtf8("actionLoad_Parameters"))
        self.actionSave_Parameters = QtGui.QAction(MainWindow)
        self.actionSave_Parameters.setObjectName(_fromUtf8("actionSave_Parameters"))
        self.actionLoad_Empty_Can = QtGui.QAction(MainWindow)
        self.actionLoad_Empty_Can.setObjectName(_fromUtf8("actionLoad_Empty_Can"))
        self.actionLoad_Detector_Background = QtGui.QAction(MainWindow)
        self.actionLoad_Detector_Background.setObjectName(_fromUtf8("actionLoad_Detector_Background"))
        self.actionLoad_Time_Channel_Background = QtGui.QAction(MainWindow)
        self.actionLoad_Time_Channel_Background.setObjectName(_fromUtf8("actionLoad_Time_Channel_Background"))
        self.actionLoad_Dark_Count = QtGui.QAction(MainWindow)
        self.actionLoad_Dark_Count.setObjectName(_fromUtf8("actionLoad_Dark_Count"))
        self.actionSet_Overall_Background_Rate = QtGui.QAction(MainWindow)
        self.actionSet_Overall_Background_Rate.setObjectName(_fromUtf8("actionSet_Overall_Background_Rate"))
        self.actionLoad_Vanadium = QtGui.QAction(MainWindow)
        self.actionLoad_Vanadium.setObjectName(_fromUtf8("actionLoad_Vanadium"))
        self.actionBy_Detector_Number = QtGui.QAction(MainWindow)
        self.actionBy_Detector_Number.setObjectName(_fromUtf8("actionBy_Detector_Number"))
        self.actionBy_Detector_Angle = QtGui.QAction(MainWindow)
        self.actionBy_Detector_Angle.setObjectName(_fromUtf8("actionBy_Detector_Angle"))
        self.actionCreateWorkspace = QtGui.QAction(MainWindow)
        self.actionCreateWorkspace.setObjectName(_fromUtf8("actionCreateWorkspace"))
        self.actionDeleteSelected = QtGui.QAction(MainWindow)
        self.actionDeleteSelected.setObjectName(_fromUtf8("actionDeleteSelected"))
        self.actionDeleteAll = QtGui.QAction(MainWindow)
        self.actionDeleteAll.setObjectName(_fromUtf8("actionDeleteAll"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSummed_Files = QtGui.QAction(MainWindow)
        self.actionSummed_Files.setObjectName(_fromUtf8("actionSummed_Files"))
        self.actionProjection_Data = QtGui.QAction(MainWindow)
        self.actionProjection_Data.setObjectName(_fromUtf8("actionProjection_Data"))
        self.actionRead_Mask_File = QtGui.QAction(MainWindow)
        self.actionRead_Mask_File.setObjectName(_fromUtf8("actionRead_Mask_File"))
        self.actionDirect = QtGui.QAction(MainWindow)
        self.actionDirect.setObjectName(_fromUtf8("actionDirect"))
        self.actionInverse = QtGui.QAction(MainWindow)
        self.actionInverse.setObjectName(_fromUtf8("actionInverse"))
        self.actionS_Q_Omega = QtGui.QAction(MainWindow)
        self.actionS_Q_Omega.setObjectName(_fromUtf8("actionS_Q_Omega"))
        self.actionSymmertrized_S_Q_Omega = QtGui.QAction(MainWindow)
        self.actionSymmertrized_S_Q_Omega.setObjectName(_fromUtf8("actionSymmertrized_S_Q_Omega"))
        self.actionD2_signal_d_Omega_d_Ef = QtGui.QAction(MainWindow)
        self.actionD2_signal_d_Omega_d_Ef.setObjectName(_fromUtf8("actionD2_signal_d_Omega_d_Ef"))
        self.actionChi_Q_omega = QtGui.QAction(MainWindow)
        self.actionChi_Q_omega.setObjectName(_fromUtf8("actionChi_Q_omega"))
        self.actionGDOS = QtGui.QAction(MainWindow)
        self.actionGDOS.setObjectName(_fromUtf8("actionGDOS"))
        self.actionVDOS = QtGui.QAction(MainWindow)
        self.actionVDOS.setObjectName(_fromUtf8("actionVDOS"))
        self.actionUnadjusted_by_ki_kf_factor = QtGui.QAction(MainWindow)
        self.actionUnadjusted_by_ki_kf_factor.setObjectName(_fromUtf8("actionUnadjusted_by_ki_kf_factor"))
        self.actionLoad_Workspace_s = QtGui.QAction(MainWindow)
        self.actionLoad_Workspace_s.setObjectName(_fromUtf8("actionLoad_Workspace_s"))
        self.actionGoniometer_Properties = QtGui.QAction(MainWindow)
        self.actionGoniometer_Properties.setObjectName(_fromUtf8("actionGoniometer_Properties"))
        self.menuDelete.addAction(self.actionDeleteSelected)
        self.menuDelete.addAction(self.actionDeleteAll)
        self.menuFile.addAction(self.actionLoad_Workspace_s)
        self.menuFile.addAction(self.actionCreateWorkspace)
        self.menuFile.addAction(self.menuDelete.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuParameters.addAction(self.actionLoad_Parameters)
        self.menuParameters.addAction(self.actionSave_Parameters)
        self.menuBackground.addAction(self.actionLoad_Empty_Can)
        self.menuBackground.addAction(self.actionLoad_Detector_Background)
        self.menuBackground.addAction(self.actionLoad_Time_Channel_Background)
        self.menuBackground.addAction(self.actionLoad_Dark_Count)
        self.menuBackground.addAction(self.actionSet_Overall_Background_Rate)
        self.menuBackground.addSeparator()
        self.menuBackground.addAction(self.actionLoad_Vanadium)
        self.menuSet_Mask.addAction(self.actionBy_Detector_Number)
        self.menuSet_Mask.addAction(self.actionBy_Detector_Angle)
        self.menuMask.addAction(self.menuSet_Mask.menuAction())
        self.menuMask.addAction(self.actionRead_Mask_File)
        self.menuInstrument_Geometry.addAction(self.actionDirect)
        self.menuInstrument_Geometry.addAction(self.actionInverse)
        self.menuVeiw_Intensity_As.addAction(self.actionS_Q_Omega)
        self.menuVeiw_Intensity_As.addAction(self.actionSymmertrized_S_Q_Omega)
        self.menuVeiw_Intensity_As.addAction(self.actionD2_signal_d_Omega_d_Ef)
        self.menuVeiw_Intensity_As.addAction(self.actionChi_Q_omega)
        self.menuVeiw_Intensity_As.addAction(self.actionGDOS)
        self.menuVeiw_Intensity_As.addAction(self.actionVDOS)
        self.menuVeiw_Intensity_As.addAction(self.actionUnadjusted_by_ki_kf_factor)
        self.menuOptions.addAction(self.menuInstrument_Geometry.menuAction())
        self.menuOptions.addAction(self.menuVeiw_Intensity_As.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionGoniometer_Properties)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuParameters.menuAction())
        self.menubar.addAction(self.menuBackground.menuAction())
        self.menubar.addAction(self.menuMask.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetFilesWorkspaces_2.setCurrentIndex(1)
        self.SampleTabWidget_2.setCurrentIndex(1)
        self.ViewTabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btnWorkspaceSave.setText(_translate("MainWindow", "Save", None))
        self.tblWorkspaces.setSortingEnabled(True)
        item = self.tblWorkspaces.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Select", None))
        item = self.tblWorkspaces.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Workspace", None))
        item = self.tblWorkspaces.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tblWorkspaces.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Saved", None))
        item = self.tblWorkspaces.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Size", None))
        self.btnWorkspaceRemove.setText(_translate("MainWindow", "Remove", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Workspace Options:", None))
        self.btnLoad.setText(_translate("MainWindow", "Load", None))
        self.btnWorkspaceGroup.setText(_translate("MainWindow", "Group Selected", None))
        self.btnWorkspaceCompose.setText(_translate("MainWindow", "Compose", None))
        self.tabWidgetFilesWorkspaces_2.setTabText(self.tabWidgetFilesWorkspaces_2.indexOf(self.tabWidgetFilesWorkspacesPage2_2), _translate("MainWindow", "Workspace Manager", None))
        self.btnStatusLog.setText(_translate("MainWindow", "Save Log", None))
        self.labelStatus_2.setText(_translate("MainWindow", "Status Area", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "System Status", None))
        self.label_132.setText(_translate("MainWindow", "Memory Usage", None))
        self.labelMaxMem_2.setText(_translate("MainWindow", "Max Mem:", None))
        self.label_164.setText(_translate("MainWindow", "CPU Usage", None))
        self.labelCPUCount_2.setText(_translate("MainWindow", "CPU count:", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Application Status", None))
        self.labelElapsedTime_2.setText(_translate("MainWindow", "Elapsed Time: 0 H  0 M", None))
        self.label_108.setText(_translate("MainWindow", "Progress", None))
        self.tabWidgetFilesWorkspaces_2.setTabText(self.tabWidgetFilesWorkspaces_2.indexOf(self.tabWidgetFilesWorkspacesPage1_2), _translate("MainWindow", "Status", None))
        self.groupBox.setTitle(_translate("MainWindow", "Projection", None))
        self.label_208.setText(_translate("MainWindow", "u1", None))
        self.cmbPowderU1.setItemText(0, _translate("MainWindow", "Energy", None))
        self.cmbPowderU1.setItemText(1, _translate("MainWindow", "|Q|", None))
        self.cmbPowderU1.setItemText(2, _translate("MainWindow", "2Theta", None))
        self.cmbPowderU1.setItemText(3, _translate("MainWindow", "Det Group Number", None))
        self.cmbPowderU1.setItemText(4, _translate("MainWindow", "Time Channel", None))
        self.label_210.setText(_translate("MainWindow", "u2", None))
        self.cmbPowderU2.setItemText(0, _translate("MainWindow", "Energy", None))
        self.cmbPowderU2.setItemText(1, _translate("MainWindow", "|Q|", None))
        self.cmbPowderU2.setItemText(2, _translate("MainWindow", "2Theta", None))
        self.cmbPowderU2.setItemText(3, _translate("MainWindow", "Det Group Number", None))
        self.cmbPowderU2.setItemText(4, _translate("MainWindow", "Time Channel", None))
        self.label.setText(_translate("MainWindow", "Units", None))
        self.btnPowderCalculateProjection.setText(_translate("MainWindow", "Calculate Projection", None))
        self.SampleTabWidget_2.setTabText(self.SampleTabWidget_2.indexOf(self.PowderTab_3), _translate("MainWindow", "Powder", None))
        self.btnSingleCheckWorkspace.setText(_translate("MainWindow", "Check Workspace", None))
        self.btnSingleSaveParams.setText(_translate("MainWindow", "Save Params", None))
        self.btnSingleLoadParams.setText(_translate("MainWindow", "Load Params", None))
        self.btnSingleDefaultParams.setText(_translate("MainWindow", "Default Params", None))
        self.groupBoxViewingAxes_3.setTitle(_translate("MainWindow", "Viewing Axes:", None))
        self.label_218.setText(_translate("MainWindow", "a*", None))
        self.label_216.setText(_translate("MainWindow", "b*", None))
        self.label_217.setText(_translate("MainWindow", "c*", None))
        self.label_219.setText(_translate("MainWindow", "Label", None))
        self.label_220.setText(_translate("MainWindow", "Fold", None))
        self.label_221.setText(_translate("MainWindow", "Center", None))
        self.label_222.setText(_translate("MainWindow", "Direction", None))
        self.label_214.setText(_translate("MainWindow", "u1", None))
        self.lneSingleAU1.setText(_translate("MainWindow", "1", None))
        self.lneSingleBU1.setText(_translate("MainWindow", "0", None))
        self.lneSingleCU1.setText(_translate("MainWindow", "0", None))
        self.lneSingleU1Label.setText(_translate("MainWindow", "H", None))
        self.lneSingleU1Center.setText(_translate("MainWindow", "0", None))
        self.cmbSingleU1Direction.setItemText(0, _translate("MainWindow", "-", None))
        self.cmbSingleU1Direction.setItemText(1, _translate("MainWindow", "Auto", None))
        self.cmbSingleU1Direction.setItemText(2, _translate("MainWindow", "+", None))
        self.label_215.setText(_translate("MainWindow", "u2", None))
        self.lneSingleAU2.setText(_translate("MainWindow", "0", None))
        self.lneSingleBU2.setText(_translate("MainWindow", "1", None))
        self.lneSingleCU2.setText(_translate("MainWindow", "0", None))
        self.lneSingleU2Label.setText(_translate("MainWindow", "K", None))
        self.lneSingleU2Center.setText(_translate("MainWindow", "0", None))
        self.cmbSingleU2Direction.setItemText(0, _translate("MainWindow", "-", None))
        self.cmbSingleU2Direction.setItemText(1, _translate("MainWindow", "Auto", None))
        self.cmbSingleU2Direction.setItemText(2, _translate("MainWindow", "+", None))
        self.label_223.setText(_translate("MainWindow", "u3", None))
        self.lneSingleAU3.setText(_translate("MainWindow", "0", None))
        self.lneSingleBU3.setText(_translate("MainWindow", "0", None))
        self.lneSingleCU3.setText(_translate("MainWindow", "1", None))
        self.lneSingleU3Label.setText(_translate("MainWindow", "L", None))
        self.lneSingleU3Center.setText(_translate("MainWindow", "0", None))
        self.cmbSingleU3Direction.setItemText(0, _translate("MainWindow", "-", None))
        self.cmbSingleU3Direction.setItemText(1, _translate("MainWindow", "Auto", None))
        self.cmbSingleU3Direction.setItemText(2, _translate("MainWindow", "+", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Info:", None))
        self.lblSingleEi.setText(_translate("MainWindow", "Ei:", None))
        self.lblSingleStartAngle.setText(_translate("MainWindow", "Start Angle:", None))
        self.btnSingleCalculateProjections.setText(_translate("MainWindow", "Calculate Projections", None))
        self.lneSingleWorkspacePrefix.setText(_translate("MainWindow", "_SCProj", None))
        self.label_233.setText(_translate("MainWindow", "Projection Workspace Suffix", None))
        self.groupBoxSCUnitCellLatticeParams_3.setTitle(_translate("MainWindow", "Unit Cell Lattice Parameters:", None))
        self.label_224.setText(_translate("MainWindow", "a(A)", None))
        self.lneSingleA.setText(_translate("MainWindow", "10", None))
        self.label_225.setText(_translate("MainWindow", "b(A)", None))
        self.lneSingleB.setText(_translate("MainWindow", "10", None))
        self.label_226.setText(_translate("MainWindow", "c(A)", None))
        self.lneSingleC.setText(_translate("MainWindow", "10", None))
        self.labelSCUCalpha_2.setText(_translate("MainWindow", "a(*)", None))
        self.lneSingleAlpha.setText(_translate("MainWindow", "90", None))
        self.labelSCUCbeta_2.setText(_translate("MainWindow", "b(*)", None))
        self.lneSingleBeta.setText(_translate("MainWindow", "90", None))
        self.labelSCUCgamma_2.setText(_translate("MainWindow", "g(*)", None))
        self.lneSingleGamma.setText(_translate("MainWindow", "90", None))
        self.groupBoxSCCrystalOrientation_3.setTitle(_translate("MainWindow", "Crystal Orientation:", None))
        self.label_227.setText(_translate("MainWindow", "ux", None))
        self.lneSingleVz.setText(_translate("MainWindow", "0", None))
        self.lneSingleUz1.setText(_translate("MainWindow", "0", None))
        self.label_229.setText(_translate("MainWindow", "uz", None))
        self.label_232.setText(_translate("MainWindow", "vz", None))
        self.lneSingleVy.setText(_translate("MainWindow", "1", None))
        self.label_231.setText(_translate("MainWindow", "vy", None))
        self.label_228.setText(_translate("MainWindow", "uy", None))
        self.lneSingleUy1.setText(_translate("MainWindow", "0", None))
        self.lneSingleVx.setText(_translate("MainWindow", "0", None))
        self.label_230.setText(_translate("MainWindow", "vx", None))
        self.lneSingleUx1.setText(_translate("MainWindow", "1", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Goniometer Settings:", None))
        self.label_234.setText(_translate("MainWindow", "Psi Offset", None))
        self.label_235.setText(_translate("MainWindow", "Motor Name", None))
        self.SampleTabWidget_2.setTabText(self.SampleTabWidget_2.indexOf(self.SingleCrystalTab_3), _translate("MainWindow", "Single Crystal", None))
        self.label_10.setText(_translate("MainWindow", "x", None))
        self.label_12.setText(_translate("MainWindow", "from", None))
        self.label_267.setText(_translate("MainWindow", "to", None))
        self.label_268.setText(_translate("MainWindow", "step", None))
        self.label_11.setText(_translate("MainWindow", "y", None))
        self.label_271.setText(_translate("MainWindow", "from", None))
        self.label_270.setText(_translate("MainWindow", "to", None))
        self.label_255.setText(_translate("MainWindow", "step", None))
        self.label_13.setText(_translate("MainWindow", "Intensity", None))
        self.label_269.setText(_translate("MainWindow", "from", None))
        self.label_266.setText(_translate("MainWindow", "to", None))
        self.rdoSliceNormToOne.setText(_translate("MainWindow", "Norm to 1", None))
        self.label_14.setText(_translate("MainWindow", "Smoothing", None))
        self.label_15.setText(_translate("MainWindow", "Colormap", None))
        self.btnSliceDisplay.setText(_translate("MainWindow", "Display", None))
        self.ViewTabWidget_2.setTabText(self.ViewTabWidget_2.indexOf(self.SliceTab_3), _translate("MainWindow", "Slice", None))
        self.label_251.setText(_translate("MainWindow", "along", None))
        self.label_4.setText(_translate("MainWindow", "from", None))
        self.label_257.setText(_translate("MainWindow", "to", None))
        self.label_256.setText(_translate("MainWindow", "step", None))
        self.label_2.setText(_translate("MainWindow", "Integrating", None))
        self.label_258.setText(_translate("MainWindow", "from", None))
        self.label_259.setText(_translate("MainWindow", "to", None))
        self.label_253.setText(_translate("MainWindow", "width", None))
        self.label_3.setText(_translate("MainWindow", "Intensity", None))
        self.label_264.setText(_translate("MainWindow", "from", None))
        self.label_265.setText(_translate("MainWindow", "to", None))
        self.rdoCutNormToOne.setText(_translate("MainWindow", "Norm to 1", None))
        self.label_5.setText(_translate("MainWindow", "Smoothing", None))
        self.btnCutPlot.setText(_translate("MainWindow", "Plot", None))
        self.btnCutSaveAscii.setText(_translate("MainWindow", "Save Ascii", None))
        self.btnCutSaveToWorkspace.setText(_translate("MainWindow", "Save to Workspace", None))
        self.btnCutPlotOver.setText(_translate("MainWindow", "Plot Over", None))
        self.ViewTabWidget_2.setTabText(self.ViewTabWidget_2.indexOf(self.CutTab_3), _translate("MainWindow", "Cut", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuDelete.setTitle(_translate("MainWindow", "Delete", None))
        self.menuParameters.setTitle(_translate("MainWindow", "Parameters", None))
        self.menuBackground.setTitle(_translate("MainWindow", "Background", None))
        self.menuMask.setTitle(_translate("MainWindow", "Mask", None))
        self.menuSet_Mask.setTitle(_translate("MainWindow", "Set Mask", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuInstrument_Geometry.setTitle(_translate("MainWindow", "Instrument Geometry", None))
        self.menuVeiw_Intensity_As.setTitle(_translate("MainWindow", "Veiw Intensity As:", None))
        self.actionLoad_Parameters.setText(_translate("MainWindow", "Load Parameters", None))
        self.actionSave_Parameters.setText(_translate("MainWindow", "Save Parameters", None))
        self.actionLoad_Empty_Can.setText(_translate("MainWindow", "Load Empty Can", None))
        self.actionLoad_Detector_Background.setText(_translate("MainWindow", "Load Detector Background", None))
        self.actionLoad_Time_Channel_Background.setText(_translate("MainWindow", "Load Time Channel Background", None))
        self.actionLoad_Dark_Count.setText(_translate("MainWindow", "Load Dark Count", None))
        self.actionSet_Overall_Background_Rate.setText(_translate("MainWindow", "Set Overall Background Rate", None))
        self.actionLoad_Vanadium.setText(_translate("MainWindow", "Load Vanadium", None))
        self.actionBy_Detector_Number.setText(_translate("MainWindow", "By Detector Number", None))
        self.actionBy_Detector_Angle.setText(_translate("MainWindow", "By Detector Angle", None))
        self.actionCreateWorkspace.setText(_translate("MainWindow", "Create Workspace from Files", None))
        self.actionDeleteSelected.setText(_translate("MainWindow", "Selected", None))
        self.actionDeleteAll.setText(_translate("MainWindow", "All", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSummed_Files.setText(_translate("MainWindow", "Summed Files", None))
        self.actionProjection_Data.setText(_translate("MainWindow", "Projection Data", None))
        self.actionRead_Mask_File.setText(_translate("MainWindow", "Read Mask File", None))
        self.actionDirect.setText(_translate("MainWindow", "Direct", None))
        self.actionInverse.setText(_translate("MainWindow", "Inverse", None))
        self.actionS_Q_Omega.setText(_translate("MainWindow", "S(Q,Omega)", None))
        self.actionSymmertrized_S_Q_Omega.setText(_translate("MainWindow", "Symmertrized S(Q,Omega)", None))
        self.actionD2_signal_d_Omega_d_Ef.setText(_translate("MainWindow", "d2(signal(/d(Omega)d(Ef)", None))
        self.actionChi_Q_omega.setText(_translate("MainWindow", "chi(Q,omega)", None))
        self.actionGDOS.setText(_translate("MainWindow", "GDOS", None))
        self.actionVDOS.setText(_translate("MainWindow", "VDOS", None))
        self.actionUnadjusted_by_ki_kf_factor.setText(_translate("MainWindow", "Unadjusted by ki/kf factor", None))
        self.actionLoad_Workspace_s.setText(_translate("MainWindow", "Load Workspace(s)", None))
        self.actionGoniometer_Properties.setText(_translate("MainWindow", "Goniometer Properties", None))

