  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set is_dev = '1' if version_number != '0' else '0' %}
  {% set version_number = '.dev' + version_number if is_dev != '0' else '' %}

  {% set version_parts = version_tag.split('.') %}
  {% set new_minor = version_parts[1]|int + 1 %}
  {% set bumped_version = version_parts[0] ~ '.' ~ new_minor %}

  {% set version = bumped_version + version_number if is_dev != '0' else version_tag %}

package:
  name: mslice
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  script: python -m pip install --ignore-installed .
  entry_points:
    - mslice = mslice.app:main

requirements:
  build:
    - python {{ python }}
    - qtpy
    - setuptools {{ setuptools }}
    - versioningit

  run:
  - python
  - pip
  - mantid
  - mantidqt
  - ipython
  - matplotlib
  - numpy
  - pre-commit
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - setuptools

test:
  imports:
    - mslice

about:
  home: https://github.com/mantidproject/mslice
  license: GPL-3.0-or-later
  summary: MSlice is a tool for visualizing cuts and slices of inelastic neutron scattering data.
