{% set version = "2.3.1" %}

package:
  name: mslice
  version: {{ version }}

source:
  #url: https://github.com/mantidproject/mslice/archive/{{ version }}.tar.gz
  #sha256: 17bb1a08c6b01361774ac119d0a5869608671403c94df26108e705083bdca896
  git_url: https://github.com/mantidproject/mslice.git
  git_tag: 592_conda_recipe

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - flake8
    - qtpy
    - setuptools

  host:
    - python
    - setuptools

  run:
  - python
  - mantid
  - mantidqt
  - ipython
  - matplotlib
  - numpy
  - pre-commit
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - six

test:
  imports:
    - mslice

about:
  home: https://github.com/mantidproject/mslice
  license: GPL-3.0-or-later
  summary: MSlice is a tool for visualizing cuts and slices of inelastic neutron scattering data.
