  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '_' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: mslice
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  script: python -m pip install --ignore-installed .
  entry_points:
    - mslice = mslice.app:main

requirements:
  build:
    - python {{ python }}
    - qtpy
    - setuptools {{ setuptools }}
    - versioningit

  run:
  - python
  - pip
  - mantid
  - mantidqt
  - ipython
  - matplotlib
  - numpy {{ numpy }}
  - pre-commit
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - setuptools
  - six

test:
  imports:
    - mslice

about:
  home: https://github.com/mantidproject/mslice
  license: GPL-3.0-or-later
  summary: MSlice is a tool for visualizing cuts and slices of inelastic neutron scattering data.
