  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '_' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: mslice
  version: {{ version }}

source:
  #url: https://github.com/mantidproject/mslice/archive/{{ version }}.tar.gz
  #sha256: 17bb1a08c6b01361774ac119d0a5869608671403c94df26108e705083bdca896
  git_url: ../  # for use with GIT_DESCRIBE_NUMBER and GIT_DESCRIBE_TAG
  #git_url: https://github.com/mantidproject/mslice.git
  #git_tag: 592_conda_recipe

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mslice = mslice.app:main

requirements:
  build:
    - python {{ python }}
    - flake8
    - qtpy
    - setuptools

  run:
  - python
  - mantid
  - mantidqt
  - ipython
  - matplotlib
  - numpy
  - pre-commit
  - pyqt
  - qtawesome
  - qtconsole
  - qtpy
  - setuptools
  - six

test:
  imports:
    - mslice

about:
  home: https://github.com/mantidproject/mslice
  license: GPL-3.0-or-later
  summary: MSlice is a tool for visualizing cuts and slices of inelastic neutron scattering data.
