name: Build and upload conda package
description: Build and upload conda package

inputs:
  repository:
    description: 'Anaconda repository'
    required: true
    default: 'mantid'
  label:
    description: 'Label'
    required: false
    default: 'nightly'
  token:
    description: 'Anaconda API Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install build tools
      shell: bash -l {0}
      run: mamba install -y -c conda-forge rattler-build anaconda-client versioningit

    - name: Build package
      shell: bash -l {0}
      run: |
        rattler-build build \
          --recipe conda/recipe.yaml \
          -c conda-forge \
          -c mantid/label/nightly \
          -c mantid \
          --variant "version=$(python -m versioningit)" \
          --output-dir output

    - name: Upload package to Anaconda.org
      shell: bash -l {0}
      env:
        ANACONDA_API_KEY: ${{ inputs.token }}
      run: |
        rattler-build upload anaconda \
          --owner ${{ inputs.repository }} \
          --channel ${{ inputs.label }} \
          output/**/*.conda