name: Build and upload conda package

inputs:
  repository:
    description: 'Anaconda repository'
    required: true
    default: 'mantid'
  label:
    description: 'Label'
    required: false
    default: 'nightly'
  token:
    description: 'Anaconda API Token'
    required: true

description: Build and upload conda package
runs:
  using: "composite"

  steps:
  - name: Make build-env
    shell: bash -l {0}
    run: |
      conda config --set always_yes yes --set changeps1 no
      conda create -n build-env python=3.8
      conda activate build-env
      conda install -c conda-forge mamba anaconda-client conda-verify
      # conda config --add channels conda-forge
      conda config --add channels mantid mantid/label/nightly
      conda config --add channels mantid/label/nightly

  - name: Build package
    shell: bash -l {0}
    run: |
      conda activate build-env
      mamba build --label ${{ inputs.label }} $GITHUB_WORKSPACE/conda
      #conda config --set anaconda_upload yes
      # if the upload silently fails - check the token expiration. Conda can fail silently!
      #mamba build --user ${{ inputs.repository }} --token ${{ inputs.token }} --label ${{ inputs.label }} $GITHUB_WORKSPACE/conda |& tee upload.log
      # Check that upload completed
      #grep "Upload complete" upload.log