#!/bin/sh
#
# Launch MSlice using the Mantid Python wrappers
#
# The build of Mantid can be controlled with arguments

# Get the directory this script resides in. This will only work on bash-like shells
SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")


INSTALL_PREFIX=/opt
PACKAGE=mantidnightly
# It is assumed that by default this script starts an IPython shell
MANTIDPYTHON=mantidpython
MANTIDPYTHON_ARGS="--matplotlib=qt4 -i"
MAIN_SCRIPT=${SCRIPT_PATH}/main.ipy

# Run
${INSTALL_PREFIX}/${PACKAGE}/bin/${MANTIDPYTHON} ${MANTIDPYTHON_ARGS} ${MAIN_SCRIPT}
