# This is a basic workflow to help you get started with Actions

name: MSlice nightly build

# Controls when the action will run. 
on:
  schedule:
    - cron: "* 2 * * *"
    
  # temporary for development
  push:
    branches:
      - conda_workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          ref: conda_workflow

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          python-version: 3.8

      - name: Install Mantid
        shell: bash -l {0}
        run: |
          sudo apt-add-repository ppa:mantid/mantid -y && sudo apt-get update -qq
          sudo apt-get install gdebi -y
          export mantiddeb=$(curl -sL https://github.com/mantidproject/download.mantidproject.org/raw/master/releases/nightly.txt | grep ubuntu)
          wget http://downloads.sourceforge.net/project/mantid/Nightly/$mantiddeb -O /tmp/mtn.deb
          sudo gdebi --option=APT::Get::force-yes=1,APT::Get::Assume-Yes=1 -n /tmp/mtn.deb
          
      - name: Install python dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r setup-requirements.txt -r install-requirements.txt -r test-requirements.txt
          echo "/opt/mantidnightly/bin:/opt/mantidnightly/lib" >> $GITHUB_PATH
          echo $PYTHONPATH

      - name: Install other dependencies
        shell: bash -l {0}
        run: |
          sudo apt-get install -y xvfb

      - name: Flake8
        shell: bash -l {0}
        run: |
          python setup.py flake8

      - name: Nosetests
        shell: bash -l {0}
        run: |
          xvfb-run '--server-args=-screen 0 640x480x24' --auto-servernum python setup.py nosetests