# This is a basic workflow to help you get started with Actions

name: MSlice nightly build

# Controls when the action will run. 
on:
  schedule:
    - cron: "* 2 * * *"
    
  # temporary for development
  push:
    branches:
      - conda_workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          python-version: 3.8

      - name: Other dependencies
        shell: bash -l {0}
        run: |
          sudo apt update -y
          sudo apt-get install -y xvfb libxcb* libxkb*
          pip install -r setup-requirements.txt -r install-requirements.txt -r test-requirements.txt
          
      - name: Flake8
        shell: bash -l {0}
        run: |
          python setup.py flake8
          
      - name: nosetests
        shell: bash -l {0}
        run: |
          xvfb-run '--server-args=-screen 0 640x480x24' --server-num=101 python setup.py nosetests
