# This is a basic workflow to help you get started with Actions

name: MSlice nightly build

# Controls when the action will run. 
on:
  schedule:
    - cron: "* 2 * * *"
    
  # temporary for development
  push:
    branches:
      - conda_workflow

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          ref: conda_workflow

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          python-version: 3.8

      - name: Install Mantid
        shell: bash -l {0}
        run: |
          wget https://sourceforge.net/projects/mantid/files/Nightly/mantidnightly_6.0.20210208.2323-0ubuntu1~bionic1_amd64.deb/download
          sudo apt install -f ./mantidnightly_6.0.20210208.2323-0ubuntu1_bionic1_amd64.deb