name: Build MSlice

on:
  workflow_run:
    workflows: ["MSlice unit tests"]
    branches: [main]
    types:
      - completed

jobs:
  build_conda_and_upload:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with: # this is only for testing and has to be removed
          fetch-depth: 0 # this is only for testing and has to be removed
          ref: 592_conda_recipe # this is only for testing and has to be removed

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: mslice-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build MSlice conda package
        run: |
          conda config --set anaconda_upload no
          conda install conda-build conda-verify
          mamba build --label unstable $GITHUB_WORKSPACE/conda
          echo "artifactName=$(basename /usr/share/miniconda3/envs/mslice-env/conda-bld/noarch/mslice-*.tar.bz2)" >> $GITHUB_ENV

      - name: Upload artifact # replace with upload to anaconda with unstable label
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: /usr/share/miniconda3/envs/mslice-env/conda-bld/noarch/mslice-*.tar.bz2
          if-no-files-found: ignore