name: Deploy MSlice nightly

on:
  workflow_run:
    workflows: ["MSlice nightly build"]
    branches: [main]
    types:
      - completed

jobs:
  build_conda_and_upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          tags: true
          ref: main

      - name: Check for changes since last build
        run: |
          echo "recentCommits=$(test -z $(git log --since="yesterday" -1 --format=%h) && echo false || echo true)" >> $GITHUB_ENV

      - name: Check whether the HEAD is tagged
        run: |
          echo "headTagged=$(test -z $(git describe --exact-match --tags) && echo false || echo true)" >> $GITHUB_ENV

      - name: Setup Miniconda
        if: ${{ env.recentCommits == 'true' && env.headTagged == 'false'}}
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge, mantid
          conda-remove-defaults: "true"
          activate-environment: mslice-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build MSlice nightly conda package
        if: ${{ env.recentCommits == 'true' && env.headTagged == 'false'}}
        uses: ./.github/actions/publish-package
        with:
          label: nightly
          token: ${{ secrets.ANACONDA_API_TOKEN }}

      - name: Remove old nightly packages
        if: ${{ env.recentCommits == 'true' && env.headTagged == 'false'}}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
          ORGANIZATION: "mantid"
          PACKAGE_NAME: "mslice"
          LABEL: "nightly"
          KEEP: "5"
          DRY_RUN: "true"
        run: |
          ANACONDA_URL="https://api.anaconda.org/package/${ORGANIZATION}/${PACKAGE_NAME}"
          RAW_RESULT=$(curl --max-time 5.5 -s ${ANACONDA_URL})
          if [ -z "${RAW_RESULT}" ]; then
            echo "Curl returned empty result"
            exit 1
          fi

          FILES_TO_REMOVE=$(echo "${RAW_RESULT}" \
            | jq -r '
              [.files[] | select(.labels | index("'"${LABEL}"'"))]
              | group_by(.version)
              | map({
                  version: .[0].version,
                  upload_time: (map(.upload_time) | max),
                  files: [.[].full_name]
                })
              | sort_by(.upload_time)
              | reverse
              | .['${KEEP}':]
              | .[].files[]
            ')

          echo "dry-run=${DRY_RUN}"
          num_removed=0
          if [ -z "${FILES_TO_REMOVE}" ]; then
            echo "No old files to remove from ${LABEL}"
          else
            echo "Removing old ${LABEL} files"
            for FILE in ${FILES_TO_REMOVE}; do
              echo "Removing ${FILE}"
              if [ "${DRY_RUN}" = "false" ]; then
                anaconda -t ${ANACONDA_TOKEN} remove --force "${FILE}"
              fi
              num_removed=$((num_removed+1))
            done
          fi
          echo "num_removed=${num_removed}"


