name: Build MSlice for OSX

on: push

jobs:
  build_conda_and_upload:
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 592_conda_recipe

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: mslice-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build MSlice conda package for OSX
        run: |
          conda config --set anaconda_upload no
          conda install conda-build conda-verify
          mamba build $GITHUB_WORKSPACE/conda

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mslice-*.tar.bz2
          path: /Users/runner/miniconda3/envs/mslice-env/conda-bld/osx-64/mslice-*.tar.bz2
          if-no-files-found: ignore