name: Build MSlice for Windows

on: push

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 592_conda_recipe

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: 3.8
          auto-activate-base: false

      - name: Create build environment
        run: |
          #conda config --set always_yes yes --set changeps1 no
          #conda create  -n build-env python=3.8
          #conda activate build-env
          conda config --set anaconda_upload no
          conda install conda-build conda-verify

      - name: Build MSlice conda package for Windows
        run: |
          #conda activate build-env
          conda config --add channels conda-forge
          conda config --add channels mantid
          conda config --add channels mantid/label/nightly
          conda build $GITHUB_WORKSPACE/conda
