name: Deploy MSlice

on:
  release:
    types: [published]

jobs:
  build_conda_and_upload:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: mslice-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build MSlice conda package
        run: |
          conda config --set anaconda_upload yes
          conda install conda-build conda-verify
          mamba build --label main --user mantid --token ${{ secrets.ANACONDA_API_TOKEN }} $GITHUB_WORKSPACE/conda