name: Deploy MSlice

on:
  release:
    types: [published]

jobs:
  build_conda_and_upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge, mantid
          conda-remove-defaults: "true"
          activate-environment: mslice-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Publish conda package
        uses: ./.github/actions/publish-package
        with:
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}