name: Build MSlice for Windows

on: push

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 592_conda_recipe

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: 3.8
          activate-environment: build-env
          auto-activate-base: false

      - name: Build MSlice conda package for Windows
        run: |
          conda config --set anaconda_upload no
          conda install conda-build conda-verify
          conda config --add channels mantid
          conda config --add channels mantid/label/nightly
          mamba build $GITHUB_WORKSPACE/conda
