name: MSlice online documentation update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Update dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install texlive-latex-base texlive-latex-recommended \
            texlive-fonts-recommended texlive-latex-extra dvipng
    - name: Build and Commit
      uses: sphinx-notes/pages@1.0
      with:
        documentation_path: docs/source
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
