name: MSlice action tests

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Mantid
        uses: ./.github/actions/publish-package
        with:
          token: ${{ secrets.ANACONDA_API_TOKEN }}