name: MSlice nightly build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout MSlice
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: mslice-env
          environment-file: environment.yml
          auto-activate-base: false
          conda-remove-defaults: "true"

      - name: Install Mantid
        run: |
          mamba install -c mantid/label/nightly mantid mantidqt

      - name: Run Tests and Coverage
        run: |
          xvfb-run '--server-args=-screen 0 640x480x24' --auto-servernum coverage run -m pytest

      - name: Report Coverage and send to Coveralls
        env:
          COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
          coverage report
